version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "payment-completed:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  payment-service:
    build: ./payment-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/e-commerce-db
    depends_on:
      - mongodb
      - kafka

  invoice-service:
    build: ./invoice-service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/e-commerce-db
    depends_on:
      - mongodb
      - kafka



volumes:
  mongodb_data: